version: '3.8'

services:
  frontend:
    build:
      context: ./react-vite
      dockerfile: Dockerfile
    ports:
      - "8383:8383"
    environment:
      - VITE_API_URL=http://backend:8001
    depends_on:
      - backend

  backend:
    build:
      context: ./full-stack-modulo-8-grupo-5
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - POSTGRES_DB=pharmacy_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./full-stack-modulo-8-grupo-5/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=pharmacy_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data: